### ISSUE TITLE
What is the difference between the r_vrp and r_svrp parameters?

### ISSUE THREAD

**Issue by cs-jlopezr** [xcsp3team/ace#4]
Impact, Activity and WdegOnDom are dynamic heuristics. It would be possible to unify the use of the parameters mentioned? Currently, Wdeg works with r_svrp but Activity and Impact just work with r_vrp.

**Comment by xcsp3team** [comment]
Dear Jheisson,

  I am currently away from my office.
I will answer you before the very end of this week.

I am going to remove the useless final for the moment.

  Best,

 Christophe

**Comment by xcsp3team** [comment]
I can add 
  (solver.restarter.numRun - solver.solutions.lastRun) % solver.head.control.restarts.varhSolResetPeriod == 0
 in the code of runReset().
This way Wdeg, Impact and Activity will be able to benefit from the two parameters.
The first one, r_vrp, indicates when resetting (of weights, impacts and activity) must be triggered (by default, this is MAX_VALUE, so never triggered)
The second one, set to 30 by default, indicates that resetting must be conducted if no solution has been found since 30 runs.
This is relevant for COP.

Are you ok with the change indicated above?

**Comment by cs-jlopezr** [comment]
Thank you very much! That's perfect. It clarifies the use!

**Comment by xcsp3team** [comment]
The use of the r_svrp parameter has been generalized.
